package nz.govt.ird.payekiwisaverdeductionscalculator;

import org.assertj.core.api.AbstractAssert;

/**
 * {@link EmployeeDetailsPage} specific assertions - Generated by CustomAssertionGenerator.
 */
public class EmployeeDetailsPageAssert extends AbstractAssert<EmployeeDetailsPageAssert, EmployeeDetailsPage> {

  /**
   * Creates a new <code>{@link EmployeeDetailsPageAssert}</code> to make assertions on actual EmployeeDetailsPage.
   * @param actual the EmployeeDetailsPage we want to make assertions on.
   */
  public EmployeeDetailsPageAssert(EmployeeDetailsPage actual) {
    super(actual, EmployeeDetailsPageAssert.class);
  }

  /**
   * An entry point for EmployeeDetailsPageAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myEmployeeDetailsPage)</code> and get specific assertion with code completion.
   * @param actual the EmployeeDetailsPage we want to make assertions on.
   * @return a new <code>{@link EmployeeDetailsPageAssert}</code>
   */
  public static EmployeeDetailsPageAssert assertThat(EmployeeDetailsPage actual) {
    return new EmployeeDetailsPageAssert(actual);
  }

}
