package nz.govt.ird.payekiwisaverdeductionscalculator;

import org.assertj.core.api.AbstractAssert;

/**
 * {@link UserAndTaxYearPage} specific assertions - Generated by CustomAssertionGenerator.
 */
public class UserAndTaxYearPageAssert extends AbstractAssert<UserAndTaxYearPageAssert, UserAndTaxYearPage> {

  /**
   * Creates a new <code>{@link UserAndTaxYearPageAssert}</code> to make assertions on actual UserAndTaxYearPage.
   * @param actual the UserAndTaxYearPage we want to make assertions on.
   */
  public UserAndTaxYearPageAssert(UserAndTaxYearPage actual) {
    super(actual, UserAndTaxYearPageAssert.class);
  }

  /**
   * An entry point for UserAndTaxYearPageAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myUserAndTaxYearPage)</code> and get specific assertion with code completion.
   * @param actual the UserAndTaxYearPage we want to make assertions on.
   * @return a new <code>{@link UserAndTaxYearPageAssert}</code>
   */
  public static UserAndTaxYearPageAssert assertThat(UserAndTaxYearPage actual) {
    return new UserAndTaxYearPageAssert(actual);
  }

}
